#!/bin/bash

(
  cd /opt/hercules || exit
  if [ -f mvs ]; then
    sh ./mvs
  else
    HERCULES_RC="$(pwd)/scripts/ipl.rc"
    export HERCULES_RC
    hercules -f "$(pwd)/conf/hercules.cnf" -d >3033.log
  fi
)