#!/bin/bash
#
# Start the hercules emulator on a configured environment.
#
# usage: hcStart <PATH_TO_HERCULES_ENVIRONMENT> <name>
# PATH_TO_HERCULES_ENVIRONMENT: The locals environment like TK4 or ZOS conofigured for hercules
# name: A name for the container to run. The name will be hercules-<name>
#
# Example:
# hcStart $HOME/TK4 tk4
#
# This will start a new hercules in the $HOME/TK4 environment and the container will be named hercules-tk4
#
# If no argument is given, it will start hercules on the TK5 environment.

if [ "_$1" = "_" ]; then
  HC_DIR="$(pwd)/mvs-tk5"
  CONTAINER_NAME="tk5"
  docker run --rm \
    -p 3270:3270 \
    -p 3278:3278 \
    -p 8038:8038 \
    --name hercules-tk5 \
    hercules-hyperion
else
  HC_DIR=$1
  CONTAINER_NAME=$2

  docker run --rm \
    -v $HC_DIR:/opt/hercules \
    -p 3270:3270 \
    -p 3278:3278 \
    -p 8038:8038 \
    --name hercules-$CONTAINER_NAME \
    hercules-hyperion
fi
